steps:
  # Install dependencies
  - name: 'node:22'
    dir: 'final-todo-app'
    entrypoint: npm
    args: ['ci']

  # Create .env file
  - name: 'node:22'
    dir: 'final-todo-app'
    entrypoint: 'npm'
    args: ['run', 'create-env', '.env']
    env:
      - 'NEXT_PUBLIC_APP_TITLE="Todo App"'
      - 'NEXT_PUBLIC_API_BASE_URL="https://ml-gcp-training-370880871422.asia-southeast1.run.app"'

  # Deploy to App Engine 
  #  args: ['app', 'deploy', '--no-promote']
    args: ['app', 'deploy']
    dir: 'final-todo-app'

timeout: '1600s' 

options:
  logging: CLOUD_LOGGING_ONLY
