name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - '${_SERVICE_NAME}'
    - '--image'
    - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    - '--region'
    - '${_DEPLOY_REGION}'
    - '--platform'
    - 'managed'
    - '--set-secrets'
    - 'DATABASE_URL=DATABASE_URL:latest'
    - '--set-env-vars'
    - 'ALLOWED_ORIGINS=${_ALLOWED_ORIGINS}'
    - '--vpc-connector'
    - 'db-connector'
    - '--add-cloudsql-instances'
    - '${_CLOUDSQL_INSTANCE}'
    - '--allow-unauthenticated'

